export const highlightCaptions = [
  'Captured in the perfect moment',
  'A memory worth saving',
  'Magic in every frame',
  'Good times and bright lights',
  'Moments made for sharing',
  'This one tells a story',
  'A highlight from the night',
  'Live for these memories',
  'The energy was unforgettable',
  'Smiles that lasted forever',
  'Feel the beat of the event',
  'Sunset vibes and laughter',
  'The crowd was electric',
  'Golden hour glow',
  'A snapshot of the celebration',
  'Memories in motion',
  'A night to remember',
  'Where every detail sparkled',
  'Cheers to great company',
  'Stories captured on camera',
  'Flashback to the best part',
  'Good vibes only',
  'Moments that matter most',
  'The highlight reel begins here',
  'An unforgettable chapter',
  'A perfect frame of the day',
  'Celebration mode activated',
  'Pure joy in a single shot',
  'A crowd full of energy',
  'A night full of color',
  'Happiest moments captured',
  'The vibe was everything',
  'Lights, music, and magic',
  'A memory frozen in time',
  'Big smiles, big memories',
  'A festive highlight',
  'Moments worth a thousand words',
  'A little sparkle from the event',
  'Captured during the best part',
  'Energy, excitement, and emotion',
  'The best moments from the night',
  'When the celebration hit its peak',
  'A highlight of the evening',
  'Those moments that make you smile',
  'Event magic in a single frame',
  'Always room for one more memory',
  'A perfect moment from the gallery',
  'A scene worth remembering',
  'A bright moment from the event',
  'Good memories, good people',
  'A visual story from the night',
  'A shot full of life',
  'This one was a crowd favorite',
  'A peak memory from the album',
  'A highlight that shines',
  'A night of unforgettable moments',
  'Captured smiles and energy',
  'A snapshot of celebration',
  'The moment the room lit up',
  'A page from the event story',
  'A favorite frame from the gallery',
  'Pure celebration captured',
  'A moment of pure joy',
  'A snapshot of the good times',
  'A highlight to remember',
  'Event energy brought to life',
  'A single frame, countless memories',
  'Celebration captured beautifully',
  'A memorable moment from the album',
  'A highlight from the party',
  'A snapshot of friends and fun',
  'The energy was in the air',
  'A picture-perfect highlight',
  'A bright memory from the night',
  'The perfect shareable moment',
  'A moment that stood out',
  'Smiles, lights, and good times',
  'A highlight from the best part',
  'A stunning event moment',
  'A snapshot from the celebration',
  'A highlight to scroll back to',
  'A beautiful memory from the gallery',
  'A moment of joy and laughter',
  'A frame full of energy',
  'One of the night’s best scenes',
  'A highlight worth saving',
  'The spirit of the event in one photo',
  'A standout memory from the album',
  'A snapshot of live celebration',
  'This moment felt unforgettable',
  'A capture full of color',
  'A highlight to share with friends',
  'An event moment frozen in time',
  'Memories from the heart of the party',
  'A highlight that tells a story',
  'Pure event excitement captured',
  'A moment worth replaying',
  'A highlight from the crowd',
  'A vivid memory from the evening',
  'A highlight that glows',
  'A beautiful frame from the night',
  'A memory that shines bright',
  'An event moment worth reliving',
  'Captured in the middle of the action',
  'A highlight with all the feels',
  'A photo that brings back the night',
  'A beautifully captured celebration',
  'A highlight straight from the album',
  'A memorable shot from the event',
  'A moment of celebration and light',
  'A highlight that sparks joy',
  'A shot full of event atmosphere',
  'A highlight to keep forever',
  'A standout photo from the gallery',
  'A share-worthy event moment',
];

const hashString = (value: string) => {
  let hash = 0;
  for (let i = 0; i < value.length; i += 1) {
    hash = (hash << 5) - hash + value.charCodeAt(i);
    hash |= 0;
  }
  return Math.abs(hash);
};

export const getCaptionForMediaId = (mediaId: string) => {
  const index = hashString(mediaId) % highlightCaptions.length;
  return highlightCaptions[index];
};
